# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 927629b9622723e3af25c0e61e24a3e19e2b96d920942a26bc439f3aacf40c8d90e1f4c91a1cc19fe310017807620d0d3ec6a7f7c52dd4fab254ac43b767b43a

test:
  secret_key_base: d5959bf166f9bd163a0e81eedffddc3756c212334fada7fc942eba3f649972a20ec3dc2208cbb0f2662c87c3a1ad9715fc4c990039f5ec5e4d421bdf62f539cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
